disabled_rules:
  - trailing_whitespace
  - todo
  - function_parameter_count
  - file_length
  - type_body_length
  - line_length
  - cyclomatic_complexity
  - identifier_name
  - nesting
  - large_tuple
  - function_body_length
  # Formatting preferences (safe to disable)
  - switch_case_alignment    # Pure formatting, 87 violations
  - for_where                # Many unfixable due to complex bodies, 24 violations
  - vertical_parameter_alignment  # Formatting preference, 1 violation

opt_in_rules:
  # - empty_count  # Disabled: False positives on integer properties
  - empty_string
  - fatal_error_message
  # - redundant_nil_coalescing  # Disabled: Needed to flatten double optionals
  - redundant_void_return
  - unused_import
  - implicit_return
  # - discouraged_optional_boolean  # Disabled: Bool? can be legitimate for tri-state

included:
  - Sources/VectorIndex
  - Tests/VectorIndexTests

excluded:
  - Sources/CAtomicsShim
  - Sources/CPQEncode
  - Sources/CS2RNG
  - Sources/VectorIndexBenchmarks
  - kernel-specs
  - migration-docs
  - tools

reporter: "xcode"

# Rule configurations
force_try:
  severity: warning  # Downgrade from error to warning in tests
